### ISSUE TITLE
[1.16.5] server crash Ticking entity

### ISSUE THREAD

**Issue by MrJorman** [MinecraftMist/Mist#10]
**Minecraft Version :** 1.16.5

**Mist Version :** mist-9

**Operating System :** Windows 10 64 bit

**Logs :** https://pastebin.com/Tgc2erZV

**Mod list :** смотрите скриншот

**Plugin list :** смотрите скриншот

**Description of issue :** сервер через какое то время сам выключается и образуется краш.

![image](https://user-images.githubusercontent.com/55187962/126144185-e22642b6-f41f-4b1d-9cc7-ea6fbd5c1302.png)
![image](https://user-images.githubusercontent.com/55187962/126144167-b4bab78f-354e-42dc-a8be-6a0b2b8a5d7c.png)

**Comment by XionioXMaster** [comment]
Попробуйте установить в server.proporties максимальное количество тиков на -1

**Comment by KR33PYK1NG** [comment]
На билдах 11+ подобные краши должны прекратиться. Если будут возникать повторно, пересоздашь/откроешь заново issue.
