### ISSUE TITLE
[1.16.5] Пила из Create ложит сервер

### ISSUE THREAD

**Issue by XionioXMaster** [MinecraftMist/Mist#13]
**Minecraft Version :** 1 16 5
**Mist Version :** 12
**Operating System :** Унбунту 20
**Concerned mod / plugin** : Plugins: https://haste.mohistmc.com/gaqihepoxu 
**Steps to Reproduce :**
 1. Использую вот эту генерацию мира: https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/
 2. Когда рублю большое дерево моментально ложит сервер
 3. Подробнее: https://youtu.be/rLiXdjygNaA
 4. Биом из дата пака /locatebiome minecraft:dark_forest_hills
 5. Возможно пила по цепочке берёт огромное количество деревьев из-за этого и происходит падение.

**Description of issue :** https://youtu.be/rLiXdjygNaA

**Logs :**  

https://paste.ubuntu.com/p/YDnxtcBrkX/

**Comment by XionioXMaster** [comment]
Как я выяснил это связано из механики пилы которая по цепочке рубит все связанные листьями деревья
https://github.com/Creators-of-Create/Create/issues/2018
Но возможно всё-таки это Mist ошибка, так что пока что оставлю открытым.

**Comment by KR33PY** [comment]
По логу пробежался: очень сомневаюсь, что ядро причастно.
Выглядит как проблема с рекурсией на стороне мода, о чем ты сам и сказал.
