### ISSUE TITLE
Ошибка 12 билда

### ISSUE THREAD

**Issue by XionioXMaster** [MinecraftMist/Mist#14]
![image](https://user-images.githubusercontent.com/86433158/126405879-f80accee-44a9-49b8-ad5d-b70f15f7f4e5.png)
Полностью чистый Mist 12 версии, после того как мир был сгенерирован, а затем перезапущен сервер, не пускает пока не отредачить data мира.

Так же условием воссоздания должен быть игрок который хотя бы 1 раз посещал мир.

Полагаю потянулось ещё с 9

**Comment by GitJhopa** [comment]
как же ты зае6ал парашник)

**Comment by KR33PY** [comment]
Не воспроизводится, проверялось на Билде 12 с чистым миром.
