### ISSUE TITLE
[1.16.5] ОЧЕНЬ ЖЕСТКИЙ БАГ ГЕНЕРАЦИЙ ABNORMALS+MIST/MOHIST

### ISSUE THREAD

**Issue by GitJhopa** [MinecraftMist/Mist#15]
**Minecraft Version :** 1.16.5

**Mist Version :** mist-12

**Operating System :** Windows 10 (64 bit)

**Logs :** нет крашей

**Mod list :** все моды от Abnormals Team

**Plugin list :** проверялось без плагинов

**Description of issue :** суть: крашаются чанки при новой генерации мира, тобишь чтобы получить поломку, необходимо сделать некие действия:

**1.** Starting server..
**2.** /worldborder center ~ ~
**3.** /worldborder set 10000
**4.** /stop
**5.** Start the server right now..
**6.** /gamemode 1
**7.** I fly around the map and load the pieces for about 1 minutes.
**8.** /stop
**9.** Start the server right now..
**10.** I fly around the map and load the pieces for about 5-10 minutes.
**11.** As soon as I entered, literally 30 seconds flew by and immediately next to my appearance I found a new broken chunk that had not been loaded before.
**12.** Sometimes you need to restart the server 2-4 times.

Проверялось в одиночном мире, на чистом Forge и ArcLight ядре - все отлично. Этот баг работает на Mohist, и на Mist, подробно описание можно прочитать тут: **https://github.com/MohistMC/Mohist/issues/1511**
![image](https://user-images.githubusercontent.com/86250668/126491863-102e4fce-1480-473d-a2f7-9d9b01c63d99.png)
![image](https://user-images.githubusercontent.com/86250668/126491873-8a330261-65f2-4d0a-9f06-b953d382decf.png)
![image](https://user-images.githubusercontent.com/86250668/126491881-60871a08-53e3-4b89-bbec-a4fe5336a853.png)
![image](https://user-images.githubusercontent.com/86250668/126491903-68fe446b-79c3-4027-a6aa-f7f67e2dc8ff.png)

**Comment by MrJorman** [comment]
как я понял фиксов не будет... ядро заброшено?

**Comment by GitJhopa** [comment]
ошибка исправлена. виновато было не ядро.

**Comment by XionioXMaster** [comment]
![Без имени](https://user-images.githubusercontent.com/86433158/127620631-e2a5a1c2-9907-460f-8b8d-cc10621182e8.png)
Желательно бы указывать что было причиной.

**Comment by MrJorman** [comment]
Чтобы я за свое просранное время и мучения делился с тобой инфой - вот уж нет

**Comment by XionioXMaster** [comment]
> Чтобы я за свое просранное время и мучения делился с тобой инфой - вот уж нет

Я тут причём? Мне абсолютно все равно, а вот **KR33PY** может быть до сих пор искал ошибку...
