### ISSUE TITLE
[1.16.5] CMI плагин и /list

### ISSUE THREAD

**Issue by XionioXMaster** [MinecraftMist/Mist#18]
**Minecraft Version :** 1.16.5
**Mist Version :** 13
**Operating System :** Унтбунту 20
**Concerned mod / plugin** : https://haste.mohistmc.com/gaqihepoxu

**Logs :** `>....=>.... [07:28:25 WARN]: java.lang.NumberFormatException: For input string: "lt"
>.... [07:28:25 WARN]: at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
>.... [07:28:25 WARN]: at java.base/java.lang.Integer.parseInt(Integer.java:652)
>.... [07:28:25 WARN]: at java.base/java.lang.Integer.parseInt(Integer.java:770)
>.... [07:28:25 WARN]: at com.Zrips.CMI.commands.list.list.perform(list.java:244)
>....[07:28:25 WARN]: at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
>.... [07:28:25 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [07:28:25 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157)
>.... [07:28:25 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:767)
>.... [07:28:25 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:753)
>.... [07:28:25 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:362)
>.... [07:28:25 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
>.... [07:28:25 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:965)
>.... [07:28:25 WARN]: at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:778)
>.... [07:28:25 WARN]: at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283)
>.... [07:28:25 WARN]: at java.base/java.lang.Thread.run(Thread.java:829)
>.... [07:28:25 WARN]: java.lang.NumberFormatException: For input string: ""
>.... [07:28:25 WARN]: at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
>.... [07:28:25 WARN]: at java.base/java.lang.Integer.parseInt(Integer.java:662)
>.... [07:28:25 WARN]: at java.base/java.lang.Integer.parseInt(Integer.java:770)
>.... [07:28:25 WARN]: at com.Zrips.CMI.commands.list.list.perform(list.java:244)
>.... [07:28:25 WARN]: at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
>.... [07:28:25 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [07:28:25 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157)
>.... [07:28:25 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:767)
>.... [07:28:25 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:753)
>.... [07:28:25 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:362)
>.... [07:28:25 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
>.... [07:28:25 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:965)
>.... [07:28:25 WARN]: at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:778)
>.... [07:28:25 WARN]: at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283)
>.... [07:28:25 WARN]: at java.base/java.lang.Thread.run(Thread.java:829)
>.... [07:28:25 WARN]: java.lang.NumberFormatException: For input string: "og"
>.... [07:28:25 WARN]: at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
>.... [07:28:25 WARN]: at java.base/java.lang.Integer.parseInt(Integer.java:652)
>.... [07:28:25 WARN]: at java.base/java.lang.Integer.parseInt(Integer.java:770)
>.... [07:28:25 WARN]: at com.Zrips.CMI.commands.list.list.perform(list.java:244)
>.... [07:28:25 WARN]: at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
>.... [07:28:25 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [07:28:25 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157)
>.... [07:28:25 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:767)
>.... [07:28:25 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:753)
>.... [07:28:25 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:362)
>.... [07:28:25 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
>.... [07:28:25 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:965)
>.... [07:28:25 WARN]: at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:778)
>.... [07:28:25 WARN]: at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283)
>.... [07:28:25 WARN]: at java.base/java.lang.Thread.run(Thread.java:829)
>.... [07:28:25 INFO]: ========================
>.... [07:28:25 INFO]: Игроки онлайн 11/76
>.... [07:28:25 INFO]: default: Icar_zero, VIVATVT, DmitregoVIP, ARTEMIKSi, Siriaaa, yutoss, JeinDeir, AIRSORCERER, Nelish
>.... [07:28:25 INFO]: gertsog: Aferios, Moloro4ik
>.... [07:28:25 INFO]: ========================`

**Steps to Reproduce :**
 1. Странный варнинг при использовании /list через консоль, думаю так же и при использоании с сервера

**Comment by KR33PY** [comment]
Не баг ядра. Проверь файл `Locale_RU.yml`, в нем путь `command.list.info.groups`.
Все ключи, которые являются дочерними по отношению к `groups`, обязаны иметь формат groupЧИСЛО.
Скорее всего, у тебя там некорректный ключ (который оканчивается на lt)
