### ISSUE TITLE
/reload bug

### ISSUE THREAD

**Issue by KubiRemPL** [MinecraftMist/Mist#20]
**Minecraft Version :** 1.16

**Mist Version :**  mist-1.16.5-13-server.jar

**Operating System :** Linux - Ubuntu 20.04

**Logs :** 
[latest.log](https://github.com/MinecraftMist/Mist/files/6868602/latest.log)

**Mod list :**  CraftTweaker-1.16.5-7.1.0.356.jar

**Plugin list :**  None

**Description of issue :** So I found that when using `/reload` command there is exception that causes reload to fail.

**Comment by KubiRemPL** [comment]
also just a sidenote - mohist 708 (that one with paper patches that were deleted) works just fine

**Comment by KR33PYK1NG** [comment]
I didn't exactly dig to find where this issue comes from, just fixed the consequence.
Looks fine, but still, let me know if you encounter any command-related problems after using /reload.
