### ISSUE TITLE
[1.16.5] Endergetic Expansion - Booflo Vest

### ISSUE THREAD

**Issue by GitJhopa** [MinecraftMist/Mist#3]
**Minecraft Version :** 1.16.5

**Mohist Version :** последняя версия

**Operating System :** Windows 10 64 bit

**Logs :** логов нет

**Mod list :** Endergetic Expansion, AbnormalsCore

**Plugin list :** дефолтные

**Description of issue :** Жилет пуфлу не работает, как надо, нажимая пробел я должен в нём прыгать, в итоге ничего не происходит, вот видео: https://youtu.be/_CgIdlT_qCk

**Comment by KR33PYK1NG** [comment]
На Endergetic Expansion 3.0.0+Mist 10 жилет работает корректно.
Используется он дабл-кликом по пробелу, если что.
