### ISSUE TITLE
Bookshelf (bookshelf) has failed to load correctly

### ISSUE THREAD

**Issue by TheTechPny** [MinecraftMist/Mist#32]
**Minecraft Version :** 1.16.5
**Mist Version :** mist-1.16.5-14-server.jar
**Operating System :** Ubuntu 18.04.1 LTS

**Logs :**
latest.log --- https://mclo.gs/cuX2Rm0
Crash report --- https://pastebin.com/raw/WWgpkY87

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}
https://pastebin.com/raw/hcX445t8

**Plugin list :** NONE

**Description of issue :** Bookshelf (bookshelf) has failed to load correctly

**Comment by KR33PYK1NG** [comment]
Cannot reproduce this with only Bookshelf installed. Looks like some type of mod conflict. Try removing mods one by one until it stops crashing.
