### ISSUE TITLE
[1.16.5] Savage&Ravage mod Mask of Dishonesty

### ISSUE THREAD

**Issue by GitJhopa** [MinecraftMist/Mist#4]
**Minecraft Version :** 1.16.5

**Mohist Version :** последняя версия

**Operating System :** Windows 10 64 bit

**Logs :** нету

**Mod list :** Savage&Ravage, Abnormals Core.

**Plugin list :** дефолтные

**Description of issue :** надевая маску Mask of Dishonesty, чаще всего она багает, невидимость просто активируется по несколько раз, иногда вообще входа в невидимость нету. Видео: https://youtu.be/Fbu48Yp1LMM

**Comment by XionioXMaster** [comment]
Plugin list : дефолтные 
Говорит о многом

**Comment by KR33PYK1NG** [comment]
Откуда взята твоя версия Savage & Ravage? В последней релизнутой версии (3.1.0) Mask of Dishonesty еще не добавлена.

**Comment by GitJhopa** [comment]
Не ту скачал

**Comment by GitJhopa** [comment]
Ты не ту версию скачал, есть еще новее.

**Comment by KR33PYK1NG** [comment]
Не воспроизводится в чистой среде. Вероятно, конфликт с другими модами/плагинами.
