### ISSUE TITLE
[1.16.5] Ice And Fire - драконы ложат сервер из-за телепорта

### ISSUE THREAD

**Issue by XionioXMaster** [MinecraftMist/Mist#7]
**Minecraft Version :** 1.16.5

**Mist Version :** 8

**Operating System :** unbuntu 20

**Concerned mod / plugin** : Ice And Fire

**Logs :** 
[latest (19).log](https://github.com/MinecraftMist/Mist/files/6836281/latest.19.log)

**Steps to Reproduce :**
1 создайте дракона
заставьте его следовать за вами, используя, посох управления драконом и произведите телепорт на свой дом, при этом не оседлав его.
Это моментально нагружает CPU и память из-за чего сервер просто падает

**Comment by KR33PY** [comment]
Опробовал самые разные комбинации, включая двух игроков, escorting и home position для дракона. В чистой среде (только ядро и мод) у меня не воспроизводится.

**Comment by KR33PY** [comment]
Благодаря крашлогу удалось разобрать вопрос.
Баг на стороне мода. Можешь передать автору, что [здесь](https://github.com/Alex-the-666/Ice_and_Fire/blob/383935d745e45da2d3342e2f1024f94229130a61/src/main/java/com/github/alexthe666/iceandfire/pathfinding/raycoms/ChunkCache.java#L56) пытается аллоцироваться огромный массив.
